Temporary Instructor
cepdnaclk/people.ce.pdn.ac.lk pull request #426
Opened 2024-10-11 16:35 UTC by neth462

2024-10-11 17:02 UTC, NuwanJ commented on _data/temporary_academic_staff.json
> +  {
@neth462  Can you add a `,` before that, and verify that there is no JSON syntax error in the file?

2024-10-11 17:03 UTC, NuwanJ requested changes

2024-10-11 17:03 UTC, NuwanJ commented on _data/temporary_academic_staff.json
> +  {
@neth462  Can you add a `,` before that, and verify that there is no JSON syntax error in the file?

2024-10-12 00:10 UTC, ishanfdo18098 commented on _data/temporary_academic_staff.json
> +    "linkedin": "www.linkedin.com/in/nethmi-dissanayake-88044a29a",
```suggestion
    "linkedin": "https://www.linkedin.com/in/nethmi-dissanayake-88044a29a",
```

2024-10-12 09:30 UTC, closed without merging